### PR TITLE
Gnome 45 Support

### PR DESCRIPTION
**Pull request by FrancescoCaracciolo**
Address #79 
- Moved to ESM imports
- Added Gnome Shell 45 SASS
- Changed color mappings to also work with sidebars introduced with libadwaita 1.4

Only note: Can't make the button to install SASS work, 
```bash
npm install --prefix ~/.local/share/gnome-shell/extensions/material-you-theme@asubbiah.com/
```
Must be run to make it work.

### CODE REVIEW

**Comment by Hedronmx** [comment]
Why not merge it? is it because of the saas button?

**Comment by FrancescoCaracciolo** [comment]
I guess it's because the owner of the repo is inactive. If there are no answer I guess I will try to make my own fork to put it on the gnome extensions website

**Comment by ak1932** [comment]
I guess the repo owner is not active. @FrancescoCaracciolo you can go forward with your fork

**Comment by avanisubbiah** [comment]
> I guess it's because the owner of the repo is inactive. If there are no answer I guess I will try to make my own fork to put it on the gnome extensions website

Yeah sorry, I'm not really able to continue maintaining this. If you'd like I can add you as a maintainer to the repo if you'd like to maintain it.

**Comment by FrancescoCaracciolo** [comment]
> > I guess it's because the owner of the repo is inactive. If there are no answer I guess I will try to make my own fork to put it on the gnome extensions website
> 
> Yeah sorry, I'm not really able to continue maintaining this. If you'd like I can add you as a maintainer to the repo if you'd like to maintain it.

Yes add me as maintainer, I'm willing to continue maintining this extension.

**Comment by avanisubbiah** [comment]
Sent you the invite, thanks!

**Comment by FrancescoCaracciolo** [comment]
Can you upload the new version on Gnome Extensions website? Also, if you think that you can't upload it in a timely fashion for the next updates, would you consider giving me access to the Gnome Extensions account so that I can upload it myself? (You can change password and email here https://extensions.gnome.org/accounts/settings)

**Comment by FrancescoCaracciolo** [comment]
> Can you upload the new version on Gnome Extensions website? Also, if you think that you can't upload it in a timely fashion for the next updates, would you consider giving me access to the Gnome Extensions account so that I can upload it myself? (You can change password and email here https://extensions.gnome.org/accounts/settings)

@avanisubbiah

**Pull request merged**
